### ISSUE TITLE
INFOGRAFIA DE HILOS-RIGOBERTORAMIREZNICOLAS

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/infografia-de-hilos-Rigoberto2001#2]
![INFOGRAFIA-HILOS_RIGOBERTORAMIREZNICOLAS](https://user-images.githubusercontent.com/79929662/117853837-7b414380-b24e-11eb-83bc-908a71b09637.png)

**Comment by IsraelNicolas61** [comment]
Calificación: 17

Calificó: Imanol García e Israel Nicolás

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
